title: Casey Hirschmann # your name (or website title) here
logo: "/images/headshot_shortcrop.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engineer with 6 years experience in optimization, visualization, and process automation turned Data Scientist. 
  I'm passionate about combining my engineering understanding of operations with the problem solving capabilities of machine learning.  
  <br><br>
  B.S. Chemical Engineering - Georgia Institute of Technology - May 2015 - 3.94 GPA
  M.S. Computer Science (Machine Learning Specialty) - Georgia Institute of Technology - Expected May 2024 - 4.0 GPA
  <br><br>
  <a href="https://www.linkedin.com/in/casey-hirschmann-7015a698/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-FJX7T6B54Z # your Google Analytics tracking ID here
